FROM node:26-alpine

WORKDIR /app

RUN apk add --no-cache bash

COPY design-tokens /app/packages/node/design-tokens
RUN node /app/packages/node/design-tokens/build.js
COPY shared-infra /app/packages/node/shared-infra
COPY web-app /app/packages/node/web-app

WORKDIR /app/packages/node/web-app

RUN npm install --prefer-offline --no-audit --no-fund || true

ENV NODE_ENV=development
ENV PORT=31400
ENV WATCHPACK_POLLING=true
ENV CHOKIDAR_USEPOLLING=true

EXPOSE 31400

CMD ["npx", "next", "dev", "-p", "31400"]
