FROM node:26-alpine

WORKDIR /app

RUN apk add --no-cache bash

COPY design-tokens /app/packages/node/design-tokens
RUN node /app/packages/node/design-tokens/build.js
COPY shared-infra /app/packages/node/shared-infra
COPY web-app /app/packages/node/web-app

WORKDIR /app/packages/node/web-app

RUN cd /app/packages/node/shared-infra && npm install --no-audit --no-fund
RUN cd /app/packages/node/web-app && npm install --no-audit --no-fund

ENV NODE_ENV=development
ENV PORT=31400
ENV WATCHPACK_POLLING=true
ENV CHOKIDAR_USEPOLLING=true

EXPOSE 31400

CMD ["npx", "next", "dev", "-p", "31400"]
